### PR TITLE
#34 Custom template and webhook override

### LINKED ISSUE #34: Allow supplying custom template
With the same logic currently in use for the webhook the plugin should allow supplying a custom template at either the job level or the project level.

If none are specified then the current defaults can be used.

### PR DESCRIPTION
**Pull request by unicolet**
Fixes #34

### CODE REVIEW

**Comment by unicolet** [comment]
Documentation for the changes have been added to README :-)

**Comment by sawanoboly** [comment]
great work, thanks 😃 😺  

Has it been tested?
I already do not have the environment of Rundeck, so the impact is not immediately understood.

**Comment by unicolet** [comment]
It' s running on our rundeck, YMMV of course:-)

**Comment by sawanoboly** [comment]
Thanks!

**Pull request merged**
